import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/taledetail">TaleDetail</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/page7">Page7</Link>
        </li>
        <li>
          <Link to="/sanctionhistory">SanctionHistory</Link>
        </li>
        <li>
          <Link to="/accountinformation">AccountInformation</Link>
        </li>
        <li>
          <Link to="/inquiryhistory">InquiryHistory</Link>
        </li>
        <li>
          <Link to="/inquiryform">InquiryForm</Link>
        </li>
        <li>
          <Link to="/customerservice">CustomerService</Link>
        </li>
        <li>
          <Link to="/page8">Page8</Link>
        </li>
        <li>
          <Link to="/page9">Page9</Link>
        </li>
        <li>
          <Link to="/pwdmodifyform">PwdModifyForm</Link>
        </li>
        <li>
          <Link to="/myreplylist">MyReplyList</Link>
        </li>
        <li>
          <Link to="/page10">Page10</Link>
        </li>
        <li>
          <Link to="/noticelist">NoticeList</Link>
        </li>
        <li>
          <Link to="/recentview">RecentView</Link>
        </li>
        <li>
          <Link to="/temptalelist">TempTaleList</Link>
        </li>
        <li>
          <Link to="/temporarystoragedelete">TemporaryStorageDelete</Link>
        </li>
        <li>
          <Link to="/pwdsendemailform">PwdSendEmailForm</Link>
        </li>
        <li>
          <Link to="/loginform">LoginForm</Link>
        </li>
        <li>
          <Link to="/page11">Page11</Link>
        </li>
        <li>
          <Link to="/registerform">RegisterForm</Link>
        </li>
        <li>
          <Link to="/pwdresetform">PwdResetForm</Link>
        </li>
        <li>
          <Link to="/registercompleted">RegisterCompleted</Link>
        </li>
        <li>
          <Link to="/talesetting">TaleSetting</Link>
        </li>
        <li>
          <Link to="/canvas">Canvas</Link>
        </li>
        <li>
          <Link to="/page13">Page13</Link>
        </li>
        <li>
          <Link to="/page17">Page17</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
